#RUN THE EMPTY CODE AND IN TERMINAL TYPE pip --version AND PRESS ENTER, IT WILL SPECIFY THE PIP VERSION WITH A DIRECTORY LOCATION WHICH MEANS PACKAGE MANAGER IS INSTALLED IN YOUR PC
#NOW TO INSTALL A PACKAGE TYPE pip install nameofthepackage IN TERMINAL AND HIT ENTER, AFTER INSTALLING YOU CAN IMPORT IT IN YOUR CODE 

